macro_rules! icon {
	($path:expr) => {
		$path
	};
}

enum Positional {
    FLANK,
    SIDE
}

enum Buff {
    FUGESTSU,
    FUKA,
}

struct Combo {
    id: u32,
    combo_potency: u16,
    kenki: u8,
    buff: Option<Buff>
}

struct GameAction<'a> {
    pub id: u32,
	pub upgrades: Option<u32>,
    pub name: &'a str,
    pub icon: &'a str,
    pub global: bool,
    pub potency: u16,
	pub aoe: bool,
    pub kenki: i8,
    pub buff: Option<Buff>,
    pub combo_action: Option<Combo>,
    pub positional: Option<Positional>
}

const GAME_ACTIONS: [GameAction<'_>;14] = [
    GameAction {
        id: 7477,
		upgrades: None,
        name: "Hakaze",
        icon: "todo!()",
        global: true,
        potency: 200,
		aoe: false,
        kenki: 5,
        buff: None,
        combo_action: None,
        positional: None,
    },
	GameAction {
		id: 36963,
		upgrades: Some(7477),
		name: "Gyofu",
		icon: icon!("todo!()"),
		global: true,
		potency: 340,
		aoe: false,
		kenki: 5,
		buff: None,
		combo_action: None,
		positional: None,
	},
    GameAction {
        id: 7478,
		upgrades: None,
        name: "Jinpu",
        icon: "todo!()",
        global: true,
        potency: 140,
		aoe: false,
        kenki: 0,
        buff: None,
        combo_action: Some(Combo {
            id: 7477,
            combo_potency: 300,
            kenki: 5,
            buff: Some(Buff::FUGESTSU),
        }),
        positional: None,
    },
    GameAction {
        id: 7486,
		upgrades: None,
        name: "Enpi",
        icon: "todo!()",
        global: true,
        potency: 100,
		aoe: false,
        kenki: 10,
        buff: None,
        combo_action: None,
        positional: None,
    },
    GameAction {
        id: 7479,
		upgrades: None,
        name: "Shifu",
        icon: "todo!()",
        global: true,
        potency: 140,
		aoe: false,
        kenki: 0,
        buff: None,
        combo_action: Some(Combo {
            id: 7477,
            combo_potency: 300,
            kenki: 5,
            buff: Some(Buff::FUKA),
        }),
        positional: None,
    },
    GameAction {
        id: 7481,
		upgrades: None,
        name: "Gekko",
        icon: "todo!()",
        global: true,
        potency: 210,
		aoe: false,
        kenki: 0,
        buff: None,
        combo_action: Some(Combo {
            id: 7478,
            combo_potency: 420,
            kenki: 10,
            buff: None,
        }),
        positional: Some(Positional::FLANK)
    },
    GameAction {
        id: 7482,
		upgrades: None,
        name: "Kasha",
		icon: "todo!()",
		global: true,
		potency: 210,
		aoe: false,
		kenki: 0,
		buff: None,
		combo_action: Some(Combo {
			id: 7479,
			combo_potency: 420,
			kenki: 10,
			buff: None,
		}),
		positional: Some(Positional::SIDE)
    },
	GameAction {
		id: 7480,
		upgrades: None,
		name: "Yukikaze",
		icon: "todo!()",
		global: true,
		potency: 160,
		aoe: false,
		kenki: 0,
		buff: None,
		combo_action: Some(Combo {
			id: 7477,
			combo_potency: 340,
			kenki: 15,
			buff: None,
		}),
		positional: None
	},
	GameAction {
		id: 7483,
		upgrades: None,
		name: "Fuga",
		icon: "todo!()",
		global: true,
		potency: 90,
		aoe: true,
		kenki: 5,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 25780,
		upgrades: Some(7483),
		name: "Fuko",
		icon: "todo!()",
		global: true,
		potency: 100,
		aoe: true,
		kenki: 10,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 7484,
		upgrades: None,
		name: "Mangetsu",
		icon: "todo!()",
		global: true,
		potency: 100,
		aoe: true,
		kenki: 0,
		buff: None,
		combo_action: Some(Combo {
			id: 7483,
			combo_potency: 120,
			kenki: 10,
			buff: Some(Buff::FUGESTSU),
		}),
		positional: None,
	},
	GameAction {
		id: 7485,
		upgrades: None,
		name: "Oka",
		icon: "todo!()",
		global: true,
		potency: 100,
		aoe: true,
		kenki: 0,
		buff: None,
		combo_action: Some(Combo {
			id: 7483,
			combo_potency: 120,
			kenki: 10,
			buff: Some(Buff::FUKA)
		}),
		positional: None,
	},
	GameAction {
		id: 7489,
		upgrades: None,
		name: "Higanbana",
		icon: "todo!()",
		global: true,
		potency: 0,
		aoe: false,
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
        id: 7498,
		upgrades: None,
        name: "Third Eye",
        icon: "todo!()",
        global: false,
        potency: 0,
		aoe: false,
        kenki: 10,
        buff: None,
        combo_action: None,
        positional: None,
    },
];