macro_rules! icon {
	($path:expr) => {
		$path
	};
}

enum Positional {
    FLANK,
    SIDE
}

enum Buff {
    FUGESTSU,
    FUKA,
	MEIKYO,
	ENPI,
	BURST,
	MEDITATE,
}

struct Combo {
    id: u32,
    combo_potency: u16,
    kenki: u8,
    buff: Option<Buff>
}

struct GameAction<'a> {
    pub id: u32,
	pub upgrades: Option<u32>,
    pub name: &'a str,
    pub icon: &'a str,
    pub global: bool,
    pub potency: u16,
	pub aoe: Option<f32>,
    pub kenki: i8,
    pub buff: Option<Buff>,
    pub combo_action: Option<Combo>,
    pub positional: Option<Positional>
}

const GAME_ACTIONS: [GameAction<'_>;38] = [
	// Combo GCDs, single target followed by AOE
    GameAction {
        id: 7477,
		upgrades: None,
        name: "Hakaze",
        icon: icon!("todo!()"),
        global: true,
        potency: 200,
		aoe: None,
        kenki: 5,
        buff: None,
        combo_action: None,
        positional: None,
    },
	GameAction {
		id: 36963,
		upgrades: Some(7477),
		name: "Gyofu",
		icon: icon!("todo!()"),
		global: true,
		potency: 340,
		aoe: None,
		kenki: 5,
		buff: None,
		combo_action: None,
		positional: None,
	},
    GameAction {
        id: 7478,
		upgrades: None,
        name: "Jinpu",
        icon: icon!("todo!()"),
        global: true,
        potency: 140,
		aoe: None,
        kenki: 0,
        buff: None,
        combo_action: Some(Combo {
            id: 7477,
            combo_potency: 300,
            kenki: 5,
            buff: Some(Buff::FUGESTSU),
        }),
        positional: None,
    },
    GameAction {
        id: 7486,
		upgrades: None,
        name: "Enpi",
        icon: icon!("todo!()"),
        global: true,
        potency: 100,
		aoe: None,
        kenki: 10,
        buff: None,
        combo_action: None,
        positional: None,
    },
    GameAction {
        id: 7481,
		upgrades: None,
        name: "Gekko",
        icon: icon!("todo!()"),
        global: true,
        potency: 210,
		aoe: None,
        kenki: 0,
        buff: None,
        combo_action: Some(Combo {
            id: 7478,
            combo_potency: 420,
            kenki: 10,
            buff: None,
        }),
        positional: Some(Positional::FLANK)
    },
    GameAction {
        id: 7482,
		upgrades: None,
        name: "Kasha",
		icon: icon!("todo!()"),
		global: true,
		potency: 210,
		aoe: None,
		kenki: 0,
		buff: None,
		combo_action: Some(Combo {
			id: 7479,
			combo_potency: 420,
			kenki: 10,
			buff: None,
		}),
		positional: Some(Positional::SIDE)
    },
	GameAction {
		id: 7480,
		upgrades: None,
		name: "Yukikaze",
		icon: icon!("todo!()"),
		global: true,
		potency: 160,
		aoe: None,
		kenki: 0,
		buff: None,
		combo_action: Some(Combo {
			id: 7477,
			combo_potency: 340,
			kenki: 15,
			buff: None,
		}),
		positional: None
	},
	GameAction {
        id: 7479,
		upgrades: None,
        name: "Shifu",
        icon: icon!("todo!()"),
        global: true,
        potency: 140,
		aoe: Some(1.0),
        kenki: 0,
        buff: None,
        combo_action: Some(Combo {
            id: 7477,
            combo_potency: 300,
            kenki: 5,
            buff: Some(Buff::FUKA),
        }),
        positional: None,
    },
	GameAction {
		id: 7483,
		upgrades: None,
		name: "Fuga",
		icon: icon!("todo!()"),
		global: true,
		potency: 90,
		aoe: Some(1.0),
		kenki: 5,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 25780,
		upgrades: Some(7483),
		name: "Fuko",
		icon: icon!("todo!()"),
		global: true,
		potency: 100,
		aoe: Some(1.0),
		kenki: 10,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 7484,
		upgrades: None,
		name: "Mangetsu",
		icon: icon!("todo!()"),
		global: true,
		potency: 100,
		aoe: Some(1.0),
		kenki: 0,
		buff: None,
		combo_action: Some(Combo {
			id: 7483,
			combo_potency: 120,
			kenki: 10,
			buff: Some(Buff::FUGESTSU),
		}),
		positional: None,
	},
	GameAction {
		id: 7485,
		upgrades: None,
		name: "Oka",
		icon: icon!("todo!()"),
		global: true,
		potency: 100,
		aoe: Some(1.0),
		kenki: 0,
		buff: None,
		combo_action: Some(Combo {
			id: 7483,
			combo_potency: 120,
			kenki: 10,
			buff: Some(Buff::FUKA)
		}),
		positional: None,
	},

	// Iaijutsu actions and other similar
	GameAction {
		// Iaijutsu exists as a palette placeholder
		id: 7867,
		upgrades: None,
		name: "Iaijutsu",
		icon: icon!("todo!()"),
		global: true,
		potency: 0,
		aoe: None,
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		// Iaijutsu exists as a palette placeholder
		id: 16483,
		upgrades: None,
		name: "Tsubame-gaeshi",
		icon: icon!("todo!()"),
		global: true,
		potency: 0,
		aoe: None,
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 7489,
		upgrades: Some(7867),
		name: "Higanbana",
		icon: icon!("todo!()"),
		global: true,
		potency: 0, // Higanbana DOT will be hardcoded in later
		aoe: None,
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 7488,
		upgrades: Some(7867),
		name: "Tenka Goken",
		icon: icon!("todo!()"),
		global: true,
		potency: 300,
		aoe: Some(1.0),
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 7487,
		upgrades: Some(7867),
		name: "Midare Setsugekka",
		icon: icon!("todo!()"),
		global: true,
		potency: 640,
		aoe: None,
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 16485,
		upgrades: Some(16483),
		name: "Kaeshi: Goken",
		icon: icon!("todo!()"),
		global: true,
		potency: 300,
		aoe: Some(1.0),
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 16486,
		upgrades: Some(16483),
		name: "Kaeshi: Setsugekka",
		icon: icon!("todo!()"),
		global: true,
		potency: 640,
		aoe: None,
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 25781,
		upgrades: Some(7867), // Considered part of Iaijutsu to handle cast time properly
		name: "Ogi Namikiri",
		icon: icon!("todo!"),
		global: true,
		potency: 1000,
		aoe: Some(0.6),
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 25782,
		upgrades: Some(16483),
		name: "Kaeshi: Namikiri",
		icon: icon!("todo!"),
		global: true,
		potency: 1000,
		aoe: Some(0.6),
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 36965,
		upgrades: Some(7488),
		name: "Tendo Goken", 
		icon: icon!("todo!()"),
		global: true,
		potency: 410,
		aoe: Some(1.0),
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 36966,
		upgrades: Some(7487),
		name: "Tendo Setsugekka",
		icon: icon!("todo!()"),
		global: true,
		potency: 1100,
		aoe: None,
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 36967,
		upgrades: Some(16485),
		name: "Tendo Kaeshi Goken",
		icon: icon!("todo!()"),
		global: true,
		potency: 410,
		aoe: Some(1.0),
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 36968,
		upgrades: Some(16486),
		name: "Tendo Kaeshi Setsugekka",
		icon: icon!("todo!()"),
		global: true,
		potency: 1100,
		aoe: None,
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},

	// OGCD actions
	GameAction {
        id: 7498,
		upgrades: None,
        name: "Third Eye",
        icon: icon!("todo!()"),
        global: false,
        potency: 0,
		aoe: None,
        kenki: 10,
        buff: None,
        combo_action: None,
        positional: None,
    },
	GameAction {
        id: 36962,
		upgrades: Some(7498),
        name: "Tengetsu",
        icon: icon!("todo!()"),
        global: false,
        potency: 0,
		aoe: None,
        kenki: 10,
        buff: None,
        combo_action: None,
        positional: None,
	},
	GameAction {
		id: 7490,
		upgrades: None,
		name: "Hissatsu: Shinten",
		icon: icon!("todo!()"),
		global: false,
		potency: 250,
		aoe: None,
		kenki: -25,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 7492,
		upgrades: None,
		name: "Hissatsu: Gyoten",
		icon: icon!("todo!()"),
		global: false,
		potency: 100,
		aoe: None,
		kenki: -10,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 7493,
		upgrades: None,
		name: "Hissatsu: Yaten",
		icon: icon!("todo!()"),
		global: false,
		potency: 100,
		aoe: None,
		kenki: -10,
		buff: Some(Buff::ENPI),
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 7491,
		upgrades: None,
		name: "Hissatsu: Kyuten",
		icon: icon!("todo!()"),
		global: false,
		potency: 100,
		aoe: Some(1.0),
		kenki: -25,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 7495,
		upgrades: None,
		name: "Hagakure",
		icon: icon!("todo!()"),
		global: false,
		potency: 0,
		aoe: None,
		kenki: 10,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 16482,
		upgrades: None,
		name: "Ikishoten",
		icon: icon!("todo!()"),
		global: false,
		potency: 0,
		aoe: None,
		kenki: 50,
		buff: Some(Buff::BURST),
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 7496,
		upgrades: None,
		name: "Hissatsu: Guren",
		icon: icon!("todo!()"),
		global: false,
		potency: 400,
		aoe: Some(1.0),
		kenki: -25,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 16481,
		upgrades: None,
		name: "Hissatsu: Senei",
		icon: icon!("todo!()"),
		global: false,
		potency: 800,
		aoe: None,
		kenki: -25,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 16487,
		upgrades: None,
		name: "Shoha",
		icon: icon!("todo!()"),
		global: false,
		potency: 640,
		aoe: Some(0.6),
		kenki: 0,
		buff: None,
		combo_action: None,
		positional: None,
	},
	GameAction {
		id: 36964,
		upgrades: None,
		name: "Zanshin",
		icon: icon!("todo!()"),
		global: false,
		potency: 940,
		aoe: Some(0.6),
		kenki: -50,
		buff: None,
		combo_action: None,
		positional: None,
	},

	// IDK how to handle meditate but its getting in here rn
	GameAction {
		id: 7497,
		upgrades: None,
		name: "Meditate",
		icon: icon!("todo!()"),
		global: true,
		potency: 0,
		aoe: None,
		kenki: 0,
		buff: Some(Buff::MEDITATE),
		combo_action: None,
		positional: None
	}
];